// <auto-generated />
using LojaRepositorios.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaRepositorios.Migrations
{
    [DbContext(typeof(LojaContexto))]
    [Migration("20230826185226_CreateProductTable")]
    partial class CreateProductTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LojaRepositorios.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(14, 2)
                        .HasColumnType("DECIMAL(14,2)")
                        .HasColumnName("PrecoUnitario");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "TV QLED Samsung 4k 50",
                            PrecoUnitario = 5949.72m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "TV OLED LG 4k 50",
                            PrecoUnitario = 5300.10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
